// <auto-generated />
using AvtoSalonConsoleApp.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvtoSalonConsoleApp.Migrations
{
    [DbContext(typeof(AvtosalonContext))]
    [Migration("20230319214720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvtoSalonConsoleApp.Data.Models.Avto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvtosalonId")
                        .HasColumnType("int");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvtosalonId");

                    b.ToTable("Avtoes");
                });

            modelBuilder.Entity("AvtoSalonConsoleApp.Data.Models.Avtosalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Avtosalons");
                });

            modelBuilder.Entity("AvtoSalonConsoleApp.Data.Models.Avto", b =>
                {
                    b.HasOne("AvtoSalonConsoleApp.Data.Models.Avtosalon", "Avtosalon")
                        .WithMany("Avtoes")
                        .HasForeignKey("AvtosalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avtosalon");
                });

            modelBuilder.Entity("AvtoSalonConsoleApp.Data.Models.Avtosalon", b =>
                {
                    b.Navigation("Avtoes");
                });
#pragma warning restore 612, 618
        }
    }
}
